### ISSUE TITLE
Make site scale between mobile and desktop devices

### ISSUE THREAD

**Issue by Soft-Devel** [shellienguyen/surf-forecast#6]
## Current Behavior

* After display gets below a certain amount, the background stops moving.

## Expected Behavior

* All part of the display should flex from small screens to large ones

## Needed Corrections

* Add media queries and test screen sizes

**Comment by ghost** [comment]
fixed responsiveness for 320px(Mobile S) 375px(Mobile M) 425px(Mobile L) 768px(Tablet) Laptop(1024px)

still figuring out how to fix responsiveness for 1440px(Laptop L) i could use some help

**Comment by nystephens** [comment]
will be looking into this today.  I am on my laptop and it is not flexing properly at any breakpoints for me.

**Comment by nystephens** [comment]
Tae and I (mostly Tae) seem to have worked out the mobile responsiveness issue.  We can reopen if we need to pursue this issue further.
