### ISSUE TITLE
Error handling for when Storm Glass fetch fails.

### ISSUE THREAD

**Issue by shellienguyen** [shellienguyen/surf-forecast#7]

**Comment by nystephens** [comment]
Will take a look at this today.

**Comment by shellienguyen** [comment]
I added a condition to catch the weather fetch error.  We need to discuss on how/where to display the weather fetch error message.

Let's also discuss what to do in case of Giphy fetch error, do we want to display some other images in case of Giphy fetch error?

**Comment by shellienguyen** [comment]
To use modals.
